import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const useDailyReportPDF = () => {
  const generateDailyReportPDF = async ({
    report,
    companySettings,
    logoUrl,
  }: {
    report: any;
    companySettings?: any;
    logoUrl?: string | null;
  }) => {
    const doc = new jsPDF("p", "pt", "a4"); // p=portrait, points, A4 size
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 40;

    // --- COLORS & STYLES ---
    const primaryColor = "#1a1a1a";
    const accentColor = "#4a90e2"; // tweakable (StackBuild blue)
    doc.setFont("helvetica", "normal");

    // --- OPTIONAL WATERMARK ---
    if (logoUrl) {
      const watermarkSize = 250;
      doc.addImage(
        logoUrl,
        "PNG",
        pageWidth / 2 - watermarkSize / 2,
        pageHeight / 2 - watermarkSize / 2,
        watermarkSize,
        watermarkSize,
        "",
        "FAST"
      );
      doc.setGState(new doc.GState({ opacity: 0.08 })); // faint watermark
    }

    // --- HEADER LOGO + COMPANY INFO ---
    if (logoUrl) {
      doc.addImage(logoUrl, "PNG", margin, 30, 80, 40, "", "FAST");
    }
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("DAILY REPORT", pageWidth / 2, 50, { align: "center" });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    if (companySettings) {
      doc.text(`${companySettings.name}`, pageWidth - margin, 40, { align: "right" });
      doc.text(`${companySettings.address}`, pageWidth - margin, 55, { align: "right" });
      doc.text(`${companySettings.phone} | ${companySettings.email}`, pageWidth - margin, 70, { align: "right" });
    }

    // --- REPORT INFORMATION SECTION ---
    autoTable(doc, {
      startY: 100,
      head: [["Jobsite", "Address", "Report Date", "Submitted By", "Time"]],
      body: [
        [
          report.jobsite || "-",
          report.address || "-",
          report.reportDate || "-",
          report.submittedBy || "-",
          report.submittedTime || "-",
        ],
      ],
      theme: "grid",
      headStyles: { fillColor: accentColor, textColor: "#fff", halign: "center" },
      styles: { fontSize: 10, cellPadding: 6 },
    });

    // --- SUMMARY SECTION ---
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Summary / Notes", margin, doc.lastAutoTable.finalY + 30);

    const summaryY = doc.lastAutoTable.finalY + 50;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const summaryText = Array.isArray(report.summary)
      ? report.summary
      : [report.summary];

    let lineY = summaryY;
    summaryText.forEach((line: string, idx: number) => {
      doc.text(`• ${line}`, margin, lineY);
      lineY += 18;
    });

    // --- PHOTOS SECTION ---
    if (report.photos && report.photos.length > 0) {
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Photos", margin, lineY + 30);

      let photoX = margin;
      let photoY = lineY + 50;
      const photoSize = 90;
      const spacing = 15;
      let count = 0;

      for (const photo of report.photos) {
        try {
          doc.addImage(photo, "JPEG", photoX, photoY, photoSize, photoSize);
        } catch (err) {
          console.warn("Photo could not be added:", err);
        }

        photoX += photoSize + spacing;
        count++;

        // wrap to next row after 4 images
        if (count % 4 === 0) {
          photoX = margin;
          photoY += photoSize + spacing;
        }
      }
    }

    // --- FOOTER ---
    doc.setFontSize(9);
    doc.setTextColor("#666");
    const generatedDate = new Date().toLocaleDateString();
    doc.text(`Generated by StackBuild • ${generatedDate}`, margin, pageHeight - 30);

    // PAGE NUMBERING (if multiple pages)
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 30, { align: "right" });
    }

    return doc.save(`Daily_Report_${report.jobsite}_${report.reportDate}.pdf`);
  };

  return { generateDailyReportPDF };
};
