// utils/pdf/useDailyReportPDF.ts
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

// Extend jsPDF to include lastAutoTable (from autotable)
interface ExtendedJsPDF extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

// ---------- Config ----------
const A4 = { w: 595.28, h: 841.89 }; // pt
const MARGIN = 40;
const HEADER_H = 72;
const FOOTER_H = 32;
const CONTENT_TOP = MARGIN + HEADER_H + 8;
const PRIMARY = "#111111";
const ACCENT = "#2563eb"; // StackBuild blue
const MUTED = "#666666";
const CARD_BG = "#f6f7fb";
const BORDER = "#E3E5EB";

type PhotoItem = {
  src: string;         // prefer dataURL (PNG/JPEG). If URL, ensure CORS-safe and pre-fetched to dataURL
  caption?: string;
  takenAt?: string;    // optional; appended to caption if present
  mime?: "PNG" | "JPEG" | "JPG" | "WEBP"; // optional hint
};

type GenerateArgs = {
  report: {
    jobsite?: string;
    address?: string;
    city?: string;
    reportDate?: string;     // formatted string already (recommended)
    submittedBy?: string;
    submittedTime?: string;
    summary?: string | string[];
    activities?: { title?: string; text: string }[]; // optional extra sections
    photos?: PhotoItem[];
  };
  companySettings?: {
    name?: string;
    address?: string;
    phone?: string;
    email?: string;
  };
  logoUrl?: string | null; // pass dataURL for best results
};

// ---------- Helpers ----------
function ensureSpace(doc: ExtendedJsPDF, needed: number) {
  const y = doc.lastAutoTable?.finalY ?? (doc as any).__cursorY ?? CONTENT_TOP;
  const bottomLimit = doc.internal.pageSize.getHeight() - MARGIN - FOOTER_H;
  if (y + needed > bottomLimit) {
    doc.addPage();
    // reset a cursor hint for non-autotable blocks
    (doc as any).__cursorY = CONTENT_TOP;
  }
}

function setCursor(doc: ExtendedJsPDF, y: number) {
  (doc as any).__cursorY = y;
}

function getCursor(doc: ExtendedJsPDF) {
  return (doc as any).__cursorY ?? CONTENT_TOP;
}

function drawHeader(doc: ExtendedJsPDF, args: GenerateArgs) {
  // background line
  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, MARGIN + HEADER_H, doc.internal.pageSize.getWidth() - MARGIN, MARGIN + HEADER_H);

  // logo (left)
  if (args.logoUrl) {
    try {
      doc.addImage(args.logoUrl, "PNG", MARGIN, MARGIN, 84, 42, "", "FAST");
    } catch { /* ignore */ }
  }

  // title (center)
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PRIMARY);
  doc.setFontSize(18);
  doc.text("DAILY REPORT", doc.internal.pageSize.getWidth() / 2, MARGIN + 26, { align: "center" });

  // company block (right)
  const rightX = doc.internal.pageSize.getWidth() - MARGIN;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  const cs = args.companySettings ?? {};
  const lines: string[] = [];
  if (cs.name) lines.push(cs.name);
  if (cs.address) lines.push(cs.address);
  const contact = [cs.phone, cs.email].filter(Boolean).join(" | ");
  if (contact) lines.push(contact);
  let y = MARGIN + 10;
  lines.forEach((l) => {
    doc.text(l, rightX, y, { align: "right" });
    y += 13;
  });
}

function drawFooter(doc: ExtendedJsPDF) {
  const pageCount = (doc as any).getNumberOfPages();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  const generatedDate = new Date().toLocaleDateString();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(`Generated by StackBuild • ${generatedDate}`, MARGIN, h - MARGIN);
    doc.text(`Page ${i} of ${pageCount}`, w - MARGIN, h - MARGIN, { align: "right" });
  }
}

function metaTable(doc: ExtendedJsPDF, report: GenerateArgs["report"]) {
  autoTable(doc, {
    startY: CONTENT_TOP,
    theme: "grid",
    styles: { font: "helvetica", fontSize: 10, cellPadding: 6, lineWidth: 0.2, lineColor: BORDER },
    headStyles: { fillColor: ACCENT, textColor: "#ffffff", halign: "center" as const },
    columnStyles: { 0: { cellWidth: 120 } },
    head: [["Jobsite", "Address", "Report Date", "Submitted By", "Time"]],
    body: [[
      report.jobsite || "-",
      report.address || report.city || "-",
      report.reportDate || "-",
      report.submittedBy || "-",
      report.submittedTime || "-",
    ]],
    didDrawPage: (data) => {
      // draw header on each page
      if (data.pageNumber === 1) return; // first page already drawn outside
      drawHeader(doc, { report, logoUrl: null });
    },
    margin: { left: MARGIN, right: MARGIN },
  });
  setCursor(doc, (doc.lastAutoTable?.finalY ?? CONTENT_TOP) + 14);
}

function cardTitle(doc: ExtendedJsPDF, title: string, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(PRIMARY);
  doc.text(title, MARGIN, y);
}

function summaryCard(doc: ExtendedJsPDF, summary: string | string[]) {
  const startY = getCursor(doc);
  ensureSpace(doc, 80);
  cardTitle(doc, "Summary", startY);

  const boxY = startY + 10;
  const boxX = MARGIN;
  const boxW = doc.internal.pageSize.getWidth() - MARGIN * 2;

  // background rounded rectangle
  doc.setFillColor(CARD_BG);
  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.6);
  (doc as any).roundedRect?.(boxX, boxY, boxW, 0, 6, 6, "F"); // height 0 -> we’ll extend after text draw

  // text
  const textY = boxY + 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(PRIMARY);
  const text = Array.isArray(summary) ? summary.join("\n\n") : summary || "-";
  const wrapped = doc.splitTextToSize(text, boxW - 20);

  // Draw paragraph with auto page breaks while simulating a card
  let y = textY;
  const bottom = doc.internal.pageSize.getHeight() - MARGIN - FOOTER_H;
  const lineH = 15;
  let boxHeight = 0;

  for (const line of wrapped) {
    if (y + lineH > bottom) {
      // close previous card box height before page break
      boxHeight = y - boxY + 8;
      // redraw the filled rect with the proper height
      doc.setPage((doc as any).getNumberOfPages());
      doc.setFillColor(CARD_BG);
      doc.setDrawColor(BORDER);
      doc.setLineWidth(0.6);
      // @ts-ignore roundedRect exists in jspdf
      (doc as any).roundedRect?.(boxX, boxY, boxW, boxHeight, 6, 6, "F");

      doc.addPage();
      drawHeader(doc, { report: {} as any, logoUrl: null }); // header for new page
      y = CONTENT_TOP;
      // new card on new page
      cardTitle(doc, "Summary (cont.)", y);
      y += 10;
      // reset new box start
      doc.setFillColor(CARD_BG);
      (doc as any).roundedRect?.(boxX, y, boxW, 0, 6, 6, "F");
      y += 16;
    }
    doc.text(line, MARGIN + 10, y);
    y += lineH;
  }

  // close last box
  boxHeight = y - (boxY);
  (doc as any).roundedRect?.(boxX, boxY, boxW, boxHeight, 6, 6, "S");
  setCursor(doc, y + 10);
}

function activitiesSection(doc: ExtendedJsPDF, activities: { title?: string; text: string }[]) {
  const startY = getCursor(doc);
  ensureSpace(doc, 40);
  cardTitle(doc, "Activities / Notes", startY);

  let y = startY + 14;
  const boxX = MARGIN;
  const boxW = doc.internal.pageSize.getWidth() - MARGIN * 2;
  const bottom = doc.internal.pageSize.getHeight() - MARGIN - FOOTER_H;

  for (const [idx, a] of activities.entries()) {
    const title = a.title ? `• ${a.title}` : `• Item ${idx + 1}`;
    const text = doc.splitTextToSize(a.text, boxW - 16);
    const blockH = 16 + text.length * 14;

    if (y + blockH > bottom) {
      doc.addPage();
      drawHeader(doc, { report: {} as any, logoUrl: null });
      y = CONTENT_TOP;
      cardTitle(doc, "Activities / Notes (cont.)", y);
      y += 14;
    }

    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(PRIMARY);
    doc.text(title, boxX + 4, y);
    y += 12;
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(PRIMARY);
    text.forEach((line: string) => {
      doc.text(line, boxX + 12, y);
      y += 14;
    });

    // divider
    doc.setDrawColor(BORDER);
    doc.setLineWidth(0.5);
    doc.line(boxX, y, boxX + boxW, y);
    y += 8;
  }
  setCursor(doc, y);
}

function safeAddImage(doc: ExtendedJsPDF, img: PhotoItem, x: number, y: number, maxW: number, maxH: number) {
  // Best result with dataURL; if URL is passed and CORS blocks, this will throw and we skip gracefully.
  const format = img.mime || (img.src.startsWith("data:image/png") ? "PNG" : "JPEG");
  try {
    // Try to get intrinsic size for better scaling when the image is already cached by jsPDF
    // @ts-ignore getImageProperties exists in jspdf
    const props = (doc as any).getImageProperties?.(img.src);
    let w = maxW, h = maxH;
    if (props?.width && props?.height) {
      const ratio = props.width / props.height;
      if (maxW / maxH > ratio) {
        h = maxH;
        w = h * ratio;
      } else {
        w = maxW;
        h = w / ratio;
      }
    }
    doc.addImage(img.src, format as any, x + (maxW - w) / 2, y + (maxH - h) / 2, w, h, "", "FAST");
    return true;
  } catch {
    return false;
  }
}

function photosSection(doc: ExtendedJsPDF, photos: PhotoItem[]) {
  if (!photos?.length) return;

  const startY = getCursor(doc);
  ensureSpace(doc, 50);
  cardTitle(doc, "Photos", startY);

  let y = startY + 14;
  const pageW = doc.internal.pageSize.getWidth();
  const innerW = pageW - MARGIN * 2;
  const bottom = doc.internal.pageSize.getHeight() - MARGIN - FOOTER_H;

  // dynamic columns (2 or 3) depending on width
  const columns = innerW >= 520 ? 3 : 2;
  const gap = 10;
  const cellW = (innerW - gap * (columns - 1)) / columns;
  const cellH = 120;

  photos.forEach((p, idx) => {
    const col = idx % columns;
    const x = MARGIN + col * (cellW + gap);

    if (idx !== 0 && col === 0) {
      // new row
      y += cellH + 28;
      if (y + cellH + 20 > bottom) {
        doc.addPage();
        drawHeader(doc, { report: {} as any, logoUrl: null });
        y = CONTENT_TOP;
        cardTitle(doc, "Photos (cont.)", y);
        y += 14;
      }
    }

    // image frame
    doc.setDrawColor(BORDER);
    doc.setLineWidth(0.5);
    doc.rect(x, y, cellW, cellH);

    // image
    safeAddImage(doc, p, x, y, cellW, cellH);

    // caption
    const captionBits = [p.caption, p.takenAt].filter(Boolean).join(" • ");
    if (captionBits) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      const wrapped = doc.splitTextToSize(captionBits, cellW - 8);
      let capY = y + cellH + 12;
      wrapped.forEach((line: string) => {
        doc.text(line, x + 4, capY);
        capY += 11;
      });
    }
  });

  // advance cursor after last row
  const rows = Math.ceil(photos.length / columns);
  const lastY = startY + 14 + rows * (cellH + 28);
  setCursor(doc, lastY);
}

// ---------- Public API ----------
export const useDailyReportPDF = () => {
  const generateDailyReportPDF = async ({ report, companySettings, logoUrl }: GenerateArgs) => {
    const doc = new jsPDF("p", "pt", "a4") as ExtendedJsPDF;

    // 1) First-page header
    drawHeader(doc, { report, companySettings, logoUrl });

    // 2) Meta table
    metaTable(doc, report);

    // 3) Summary card
    if (report.summary && (Array.isArray(report.summary) ? report.summary.join("").trim() : String(report.summary).trim())) {
      summaryCard(doc, report.summary!);
    }

    // 4) Optional activities
    if (report.activities?.length) {
      activitiesSection(doc, report.activities);
    }

    // 5) Photos
    if (report.photos?.length) {
      photosSection(doc, report.photos);
    }

    // 6) Footer + page numbers
    drawFooter(doc);

    // 7) Save
    const safeJobsite = (report.jobsite || "Jobsite").replace(/[^\w\d\-_. ]+/g, "");
    const safeDate = (report.reportDate || "").replace(/[^\w\d\-_. ]+/g, "");
    doc.save(`Daily_Report_${safeJobsite}_${safeDate}.pdf`);
  };

  return { generateDailyReportPDF };
};
