
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { Invoice, CreateInvoiceData } from '@/components/admin/types/invoice';
import { useAuth } from '@/contexts/SupabaseAuthContext';

// Build a user-friendly message, calling out duplicate invoice numbers explicitly
const describeInvoiceError = (error: any, fallback: string): string => {
  const msg = String(error?.message || '');
  if (/already exists/i.test(msg) || error?.code === '23505') {
    const match = msg.match(/Invoice number (.+?) already exists/i);
    const num = match?.[1]?.trim();
    return num
      ? `Invoice number ${num} is already used in your company. Please pick a different number.`
      : 'That invoice number is already used in your company. Please pick a different number.';
  }
  return fallback;
};


export const useInvoices = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { user } = useAuth();

  // Fetch company logo URL for invoices
  const { data: companyLogoUrl } = useQuery({
    queryKey: ['company-logo-url', user?.companyId],
    queryFn: async () => {
      if (!user?.companyId) return null;
      
      const { data, error } = await supabase
        .from('companies')
        .select('logo_url')
        .eq('id', user.companyId)
        .single();

      if (error) {
        console.error('Error fetching company logo URL:', error);
        return null;
      }

      return data?.logo_url || null;
    },
    enabled: !!user?.companyId,
  });

  // Fetch invoices with company isolation
  const { data: invoices = [], isLoading, error } = useQuery({
    queryKey: ['invoices', user?.companyId],
    queryFn: async () => {
      console.log('Fetching invoices for company:', user?.companyId);
      
      if (!user?.companyId) {
        console.log('No company ID available');
        return [];
      }
      
      const { data, error } = await supabase
        .from('invoices')
        .select(`
          *,
          jobsites(name, address),
          invoice_line_items(*)
        `)
        .eq('company_id', user.companyId)
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Error fetching invoices:', error);
        throw error;
      }

      console.log('Fetched invoices:', data);
      return data as Invoice[];
    },
    enabled: !!user?.companyId,
  });

  // Create invoice
  const createInvoiceMutation = useMutation({
    mutationFn: async (invoiceData: CreateInvoiceData & { sendEmail?: boolean }) => {
      console.log('Creating invoice:', invoiceData);
      
      if (!user?.companyId) {
        throw new Error('Company ID is required to create invoices');
      }
      
      // Compute totals so they are persisted (DB defaults them to 0 otherwise)
      const subtotal = invoiceData.line_items.reduce(
        (sum, item) => sum + (Number(item.amount) || 0),
        0
      );
      const discountAmount = subtotal * ((Number(invoiceData.discount) || 0) / 100);
      const taxAmount = (subtotal - discountAmount) * ((Number(invoiceData.tax) || 0) / 100);
      const totalAmount = subtotal - discountAmount + taxAmount;

      // Create the invoice first - invoice_number will be auto-generated by the database trigger
      const insertData = {
        title: invoiceData.title,
        invoice_number: invoiceData.invoice_number || null,
        client_id: invoiceData.client_id || null,
        client_company: invoiceData.client_company,
        client_email: invoiceData.client_email,
        client_address: invoiceData.client_address,
        client_phone: invoiceData.client_phone,
        discount: invoiceData.discount || 0,
        tax: invoiceData.tax || 0,
        subtotal,
        total_amount: totalAmount,
        due_date: invoiceData.due_date,
        notes: invoiceData.notes,
        company_id: user.companyId,
      } as any; // Type assertion to work around TypeScript schema mismatch

      const { data: invoice, error: invoiceError } = await supabase
        .from('invoices')
        .insert(insertData)
        .select()
        .single();

      if (invoiceError) {
        console.error('Error creating invoice:', invoiceError);
        throw invoiceError;
      }

      // Create line items
      if (invoiceData.line_items.length > 0) {
        const { error: lineItemsError } = await supabase
          .from('invoice_line_items')
          .insert(
            invoiceData.line_items.map(item => ({
              invoice_id: invoice.id,
              description: item.description,
              quantity: item.quantity,
              unit_price: item.unit_price,
              amount: item.amount,
            }))
          );

        if (lineItemsError) {
          console.error('Error creating line items:', lineItemsError);
          throw lineItemsError;
        }
      }

      // If sendEmail flag is set, fetch complete invoice data with line items
      if (invoiceData.sendEmail) {
        const { data: completeInvoice, error: fetchError } = await supabase
          .from('invoices')
          .select(`
            *,
            jobsites(name, address),
            invoice_line_items(*)
          `)
          .eq('id', invoice.id)
          .single();

        if (fetchError) {
          console.error('Error fetching complete invoice:', fetchError);
          return invoice;
        }

        return { ...completeInvoice, _shouldSendEmail: true };
      }

      return invoice;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices', user?.companyId] });
      queryClient.invalidateQueries({ queryKey: ['company-logo-url', user?.companyId] });
      toast({
        title: 'Invoice Created',
        description: 'Invoice has been created successfully.',
      });
    },
    onError: (error) => {
      console.error('Error creating invoice:', error);
      toast({
        title: 'Error',
        description: describeInvoiceError(error, 'Failed to create invoice. Please try again.'),
        variant: 'destructive',
      });
    },
  });

  // Update invoice status
  const updateInvoiceStatusMutation = useMutation({
    mutationFn: async ({ id, status, receipt_file_url }: { 
      id: string; 
      status: 'pending' | 'paid' | 'expired';
      receipt_file_url?: string;
    }) => {
      const updateData: any = { 
        status,
        updated_at: new Date().toISOString()
      };
      
      if (receipt_file_url) {
        updateData.receipt_file_url = receipt_file_url;
      }

      const { data, error } = await supabase
        .from('invoices')
        .update(updateData)
        .eq('id', id)
        .eq('company_id', user?.companyId)
        .select()
        .single();

      if (error) throw error;
      return { data, status };
    },
    onSuccess: async (result) => {
      const { status, data: updatedInvoice } = result;
      
      queryClient.invalidateQueries({ queryKey: ['invoices', user?.companyId] });
      
      // Auto-send receipt email if status changed to 'paid'
      if (status === 'paid') {
        try {
          // Fetch complete invoice with line items
          const { data: completeInvoice, error } = await supabase
            .from('invoices')
            .select(`
              *,
              invoice_line_items (*),
              jobsites (name, address)
            `)
            .eq('id', updatedInvoice.id)
            .single();

          if (error) throw error;

          if (completeInvoice) {
            // Dynamic import to avoid circular dependencies
            const { autoSendPaidReceiptEmail } = await import('@/utils/autoSendPaidReceiptEmail');
            
            // Get company settings
            const { data: companyData } = await supabase
              .from('companies')
              .select('*')
              .eq('id', user?.companyId)
              .single();

            const receiptResult = await autoSendPaidReceiptEmail(
              completeInvoice,
              companyData || null,
              companyLogoUrl
            );

            if (receiptResult.success) {
              toast({
                title: '✅ Payment Receipt Sent',
                description: `Receipt emailed to ${completeInvoice.client_email}`,
              });
            } else {
              console.warn('Receipt email failed:', receiptResult.error);
              toast({
                title: 'Invoice Marked as PAID',
                description: 'Receipt email failed to send. You can resend manually.',
                variant: 'default',
              });
            }
          }
        } catch (error) {
          console.error('Error sending receipt email:', error);
          // Don't show error toast - invoice was still updated successfully
        }
      }
      
      // Show success toast for status update
      if (status !== 'paid') {
        toast({
          title: 'Invoice Updated',
          description: 'Invoice status has been updated successfully.',
        });
      }
    },
    onError: (error) => {
      console.error('Error updating invoice:', error);
      toast({
        title: 'Error',
        description: 'Failed to update invoice status. Please try again.',
        variant: 'destructive',
      });
    },
  });

  // Delete invoice
  const deleteInvoiceMutation = useMutation({
    mutationFn: async (invoiceId: string) => {
      console.log('Deleting invoice:', invoiceId);
      
      if (!user?.companyId) {
        throw new Error('Company ID is required to delete invoices');
      }

      // Clear child references first so foreign-key constraints don't block the
      // delete (a quote can reference the invoice it was converted into; line
      // items / payments are owned children).
      await supabase.from('quotes').update({ invoice_id: null }).eq('invoice_id', invoiceId);
      await supabase.from('invoice_payments').delete().eq('invoice_id', invoiceId);
      await supabase.from('invoice_line_items').delete().eq('invoice_id', invoiceId);

      const { error } = await supabase
        .from('invoices')
        .delete()
        .eq('id', invoiceId)
        .eq('company_id', user.companyId); // Ensure company isolation

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices', user?.companyId] });
      toast({
        title: 'Invoice Deleted',
        description: 'Invoice has been deleted successfully.',
      });
    },
    onError: (error) => {
      console.error('Error deleting invoice:', error);
      toast({
        title: 'Error',
        description: 'Failed to delete invoice. Please try again.',
        variant: 'destructive',
      });
    },
  });

  // Update invoice (full edit, including line items)
  const updateInvoiceMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: CreateInvoiceData }) => {
      if (!user?.companyId) {
        throw new Error('Company ID is required to update invoices');
      }

      const updatePayload = {
        title: data.title,
        invoice_number: data.invoice_number || undefined,
        client_id: data.client_id || null,
        client_company: data.client_company,
        client_email: data.client_email,
        client_address: data.client_address || null,
        client_phone: data.client_phone || null,
        jobsite_id: (data as any).jobsite_id || null,
        discount: data.discount || 0,
        tax: data.tax || 0,
        due_date: data.due_date,
        notes: data.notes,
        updated_at: new Date().toISOString(),
      } as any;

      // Drop invoice_number if empty so the DB keeps the existing value
      if (!updatePayload.invoice_number) delete updatePayload.invoice_number;

      const { data: updated, error: updateError } = await supabase
        .from('invoices')
        .update(updatePayload)
        .eq('id', id)
        .eq('company_id', user.companyId)
        .select()
        .single();

      if (updateError) {
        console.error('Error updating invoice:', updateError);
        throw updateError;
      }

      // Replace line items: remove existing, then insert the new set
      await supabase.from('invoice_line_items').delete().eq('invoice_id', id);

      const cleanItems = data.line_items.filter(
        (item) => item.description && item.quantity > 0 && item.unit_price > 0
      );

      if (cleanItems.length > 0) {
        const { error: itemsError } = await supabase
          .from('invoice_line_items')
          .insert(
            cleanItems.map((item) => ({
              invoice_id: id,
              description: item.description,
              quantity: item.quantity,
              unit_price: item.unit_price,
              amount: item.quantity * item.unit_price,
            }))
          );

        if (itemsError) {
          console.error('Error updating line items:', itemsError);
          throw itemsError;
        }
      }

      // Return the complete, refreshed invoice (with line items) for resend
      const { data: complete } = await supabase
        .from('invoices')
        .select(`
          *,
          jobsites(name, address),
          invoice_line_items(*)
        `)
        .eq('id', id)
        .single();

      return (complete || updated) as Invoice;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices', user?.companyId] });
      queryClient.invalidateQueries({ queryKey: ['invoice'] });
      toast({
        title: 'Invoice Updated',
        description: 'Invoice has been updated successfully.',
      });
    },
    onError: (error) => {
      console.error('Error updating invoice:', error);
      toast({
        title: 'Error',
        description: 'Failed to update invoice. Please try again.',
        variant: 'destructive',
      });
    },
  });

  return {
    invoices,
    isLoading,
    error,
    companyLogoUrl,
    createInvoice: createInvoiceMutation.mutate,
    createInvoiceMutation, // Export full mutation for custom onSuccess
    isCreating: createInvoiceMutation.isPending,
    updateInvoiceStatus: updateInvoiceStatusMutation.mutate,
    isUpdating: updateInvoiceStatusMutation.isPending,
    updateInvoice: updateInvoiceMutation.mutate,
    updateInvoiceMutation,
    isUpdatingInvoice: updateInvoiceMutation.isPending,
    deleteInvoice: deleteInvoiceMutation.mutate,
    isDeleting: deleteInvoiceMutation.isPending,
  };
};
